/* AUTO-GENERATED by extract_traces.py. Do not edit. */
/* Include from exactly one translation unit. */
#ifndef JIGSAW_TRACES_H
#define JIGSAW_TRACES_H

#include <linux/types.h>
#include <linux/kernel.h>  /* ARRAY_SIZE */

enum trace_kind {
    TRACE_BULK_H2D = 0,
    TRACE_BULK_D2H = 1,
    TRACE_BUNDLE   = 2,
};

struct trace_event {
    u8  kind;
    u64 h2d_size;       /* bytes; BULK_H2D, BUNDLE */
    u64 d2h_size;       /* bytes; BULK_D2H, BUNDLE */
    u64 cycles;         /* BUNDLE only */
    int original_count; /* raw events folded into this entry */
};

#define JIGSAW_TRACE_MAX_BYTES 1228800ULL
#define JIGSAW_BUNDLE_THRESHOLD 256ULL  /* small <=> <= this */

static const struct trace_event tr_bfs[] = {
    { 0, 32768ULL, 0ULL, 0ULL, 1 },
    { 0, 32768ULL, 0ULL, 0ULL, 1 },
    { 0, 98304ULL, 0ULL, 0ULL, 1 },
    { 0, 98304ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 16384ULL, 0ULL, 0ULL, 1 },
    { 0, 16384ULL, 0ULL, 0ULL, 1 },
    { 0, 29896ULL, 0ULL, 0ULL, 1 },
    { 2, 74ULL, 0ULL, 149573ULL, 4 },
    { 2, 64ULL, 1ULL, 136420ULL, 3 },
    { 2, 73ULL, 0ULL, 140956ULL, 3 },
    { 2, 64ULL, 1ULL, 130555ULL, 3 },
    { 2, 73ULL, 0ULL, 148911ULL, 3 },
    { 2, 64ULL, 1ULL, 135888ULL, 3 },
    { 2, 73ULL, 0ULL, 193950ULL, 3 },
    { 2, 64ULL, 1ULL, 147829ULL, 3 },
    { 2, 73ULL, 0ULL, 318273ULL, 3 },
    { 2, 64ULL, 1ULL, 146858ULL, 3 },
    { 2, 73ULL, 0ULL, 284353ULL, 3 },
    { 2, 64ULL, 1ULL, 135383ULL, 3 },
    { 2, 73ULL, 0ULL, 151490ULL, 3 },
    { 2, 64ULL, 1ULL, 136141ULL, 3 },
    { 2, 73ULL, 0ULL, 134923ULL, 3 },
    { 2, 64ULL, 1ULL, 129448ULL, 3 },
    { 1, 0ULL, 16384ULL, 0ULL, 1 },
};

static const struct trace_event tr_blackscholes[] = {
    { 0, 1024ULL, 0ULL, 0ULL, 1 },
    { 0, 1024ULL, 0ULL, 0ULL, 1 },
    { 0, 1024ULL, 0ULL, 0ULL, 1 },
    { 0, 33608ULL, 0ULL, 0ULL, 1 },
    { 2, 76ULL, 0ULL, 3102206ULL, 2 },
    { 1, 0ULL, 1024ULL, 0ULL, 1 },
    { 1, 0ULL, 1024ULL, 0ULL, 1 },
};

static const struct trace_event tr_conv3[] = {
    { 0, 67600ULL, 0ULL, 0ULL, 1 },
    { 0, 29736ULL, 0ULL, 0ULL, 1 },
    { 2, 100ULL, 0ULL, 636010ULL, 3 },
    { 1, 0ULL, 65536ULL, 0ULL, 1 },
};

static const struct trace_event tr_dotproduct[] = {
    { 0, 262144ULL, 0ULL, 0ULL, 1 },
    { 0, 262144ULL, 0ULL, 0ULL, 1 },
    { 0, 29592ULL, 0ULL, 0ULL, 1 },
    { 2, 60ULL, 0ULL, 821407ULL, 2 },
    { 1, 0ULL, 65536ULL, 0ULL, 1 },
};

static const struct trace_event tr_guassian[] = {
    { 0, 16384ULL, 0ULL, 0ULL, 1 },
    { 0, 16384ULL, 0ULL, 0ULL, 1 },
    { 0, 29880ULL, 0ULL, 0ULL, 1 },
    { 2, 320ULL, 0ULL, 35561ULL, 3 },
    { 2, 64ULL, 0ULL, 164851ULL, 2 },
    { 2, 64ULL, 0ULL, 30564ULL, 2 },
    { 2, 64ULL, 0ULL, 165375ULL, 2 },
    { 2, 64ULL, 0ULL, 30585ULL, 2 },
    { 2, 64ULL, 0ULL, 163500ULL, 2 },
    { 2, 64ULL, 0ULL, 30664ULL, 2 },
    { 2, 64ULL, 0ULL, 161707ULL, 2 },
    { 2, 64ULL, 0ULL, 30549ULL, 2 },
    { 2, 64ULL, 0ULL, 158955ULL, 2 },
    { 2, 64ULL, 0ULL, 30650ULL, 2 },
    { 2, 64ULL, 0ULL, 158798ULL, 2 },
    { 2, 64ULL, 0ULL, 30538ULL, 2 },
    { 2, 64ULL, 0ULL, 157251ULL, 2 },
    { 2, 64ULL, 0ULL, 30431ULL, 2 },
    { 2, 64ULL, 0ULL, 156494ULL, 2 },
    { 2, 64ULL, 0ULL, 30591ULL, 2 },
    { 2, 64ULL, 0ULL, 153276ULL, 2 },
    { 2, 64ULL, 0ULL, 30439ULL, 2 },
    { 2, 64ULL, 0ULL, 151747ULL, 2 },
    { 2, 64ULL, 0ULL, 30566ULL, 2 },
    { 2, 64ULL, 0ULL, 153628ULL, 2 },
    { 2, 64ULL, 0ULL, 30747ULL, 2 },
    { 2, 64ULL, 0ULL, 148751ULL, 2 },
    { 2, 64ULL, 0ULL, 31593ULL, 2 },
    { 2, 64ULL, 0ULL, 151427ULL, 2 },
    { 2, 64ULL, 0ULL, 30492ULL, 2 },
    { 2, 64ULL, 0ULL, 150069ULL, 2 },
    { 2, 64ULL, 0ULL, 30628ULL, 2 },
    { 2, 64ULL, 0ULL, 146066ULL, 2 },
    { 2, 64ULL, 0ULL, 30290ULL, 2 },
    { 2, 64ULL, 0ULL, 147153ULL, 2 },
    { 2, 64ULL, 0ULL, 29926ULL, 2 },
    { 2, 64ULL, 0ULL, 146584ULL, 2 },
    { 2, 64ULL, 0ULL, 30393ULL, 2 },
    { 2, 64ULL, 0ULL, 145035ULL, 2 },
    { 2, 64ULL, 0ULL, 31452ULL, 2 },
    { 2, 64ULL, 0ULL, 143658ULL, 2 },
    { 2, 64ULL, 0ULL, 31331ULL, 2 },
    { 2, 64ULL, 0ULL, 141720ULL, 2 },
    { 2, 64ULL, 0ULL, 31351ULL, 2 },
    { 2, 64ULL, 0ULL, 143275ULL, 2 },
    { 2, 64ULL, 0ULL, 31297ULL, 2 },
    { 2, 64ULL, 0ULL, 142233ULL, 2 },
    { 2, 64ULL, 0ULL, 30405ULL, 2 },
    { 2, 64ULL, 0ULL, 142091ULL, 2 },
    { 2, 64ULL, 0ULL, 30448ULL, 2 },
    { 2, 64ULL, 0ULL, 143200ULL, 2 },
    { 2, 64ULL, 0ULL, 30377ULL, 2 },
    { 2, 64ULL, 0ULL, 139102ULL, 2 },
    { 2, 64ULL, 0ULL, 30125ULL, 2 },
    { 2, 64ULL, 0ULL, 140895ULL, 2 },
    { 2, 64ULL, 0ULL, 30067ULL, 2 },
    { 2, 64ULL, 0ULL, 140519ULL, 2 },
    { 2, 64ULL, 0ULL, 31440ULL, 2 },
    { 2, 64ULL, 0ULL, 141036ULL, 2 },
    { 2, 64ULL, 0ULL, 31534ULL, 2 },
    { 2, 64ULL, 0ULL, 140427ULL, 2 },
    { 2, 64ULL, 0ULL, 30347ULL, 2 },
    { 2, 64ULL, 0ULL, 157942ULL, 2 },
    { 2, 64ULL, 0ULL, 30682ULL, 2 },
    { 2, 64ULL, 0ULL, 155928ULL, 2 },
    { 2, 64ULL, 0ULL, 30510ULL, 2 },
    { 2, 64ULL, 0ULL, 148347ULL, 2 },
    { 2, 64ULL, 0ULL, 30202ULL, 2 },
    { 2, 64ULL, 0ULL, 138199ULL, 2 },
    { 2, 64ULL, 0ULL, 31243ULL, 2 },
    { 2, 64ULL, 0ULL, 139308ULL, 2 },
    { 2, 64ULL, 0ULL, 31083ULL, 2 },
    { 2, 64ULL, 0ULL, 138574ULL, 2 },
    { 2, 64ULL, 0ULL, 31123ULL, 2 },
    { 2, 64ULL, 0ULL, 136471ULL, 2 },
    { 2, 64ULL, 0ULL, 31050ULL, 2 },
    { 2, 64ULL, 0ULL, 136398ULL, 2 },
    { 2, 64ULL, 0ULL, 30849ULL, 2 },
    { 2, 64ULL, 0ULL, 135640ULL, 2 },
    { 2, 64ULL, 0ULL, 31166ULL, 2 },
    { 2, 64ULL, 0ULL, 135319ULL, 2 },
    { 2, 64ULL, 0ULL, 31186ULL, 2 },
    { 2, 64ULL, 0ULL, 132663ULL, 2 },
    { 2, 64ULL, 0ULL, 31179ULL, 2 },
    { 2, 64ULL, 0ULL, 133388ULL, 2 },
    { 2, 64ULL, 0ULL, 31300ULL, 2 },
    { 2, 64ULL, 0ULL, 132306ULL, 2 },
    { 2, 64ULL, 0ULL, 31187ULL, 2 },
    { 2, 64ULL, 0ULL, 132672ULL, 2 },
    { 2, 64ULL, 0ULL, 30138ULL, 2 },
    { 2, 64ULL, 0ULL, 132460ULL, 2 },
    { 2, 64ULL, 0ULL, 31025ULL, 2 },
    { 2, 64ULL, 0ULL, 131368ULL, 2 },
    { 2, 64ULL, 0ULL, 29873ULL, 2 },
    { 2, 64ULL, 0ULL, 131372ULL, 2 },
    { 2, 64ULL, 0ULL, 30011ULL, 2 },
    { 2, 64ULL, 0ULL, 131199ULL, 2 },
    { 2, 64ULL, 0ULL, 30025ULL, 2 },
    { 2, 64ULL, 0ULL, 130541ULL, 2 },
    { 2, 64ULL, 0ULL, 30032ULL, 2 },
    { 2, 64ULL, 0ULL, 130646ULL, 2 },
    { 2, 64ULL, 0ULL, 31030ULL, 2 },
    { 2, 64ULL, 0ULL, 131007ULL, 2 },
    { 2, 64ULL, 0ULL, 29930ULL, 2 },
    { 2, 64ULL, 0ULL, 130717ULL, 2 },
    { 2, 64ULL, 0ULL, 30817ULL, 2 },
    { 2, 64ULL, 0ULL, 128981ULL, 2 },
    { 2, 64ULL, 0ULL, 30771ULL, 2 },
    { 2, 64ULL, 0ULL, 129269ULL, 2 },
    { 2, 64ULL, 0ULL, 29740ULL, 2 },
    { 2, 64ULL, 0ULL, 129847ULL, 2 },
    { 2, 64ULL, 0ULL, 29744ULL, 2 },
    { 2, 64ULL, 0ULL, 130252ULL, 2 },
    { 2, 64ULL, 0ULL, 29724ULL, 2 },
    { 2, 64ULL, 0ULL, 129485ULL, 2 },
    { 2, 64ULL, 0ULL, 29731ULL, 2 },
    { 2, 64ULL, 0ULL, 128888ULL, 2 },
    { 2, 64ULL, 0ULL, 29679ULL, 2 },
    { 2, 64ULL, 0ULL, 128602ULL, 2 },
    { 2, 64ULL, 0ULL, 30719ULL, 2 },
    { 2, 64ULL, 0ULL, 128767ULL, 2 },
    { 2, 64ULL, 0ULL, 30847ULL, 2 },
    { 2, 64ULL, 0ULL, 126284ULL, 2 },
    { 2, 64ULL, 0ULL, 30818ULL, 2 },
    { 2, 64ULL, 0ULL, 126762ULL, 2 },
    { 2, 64ULL, 0ULL, 29960ULL, 2 },
    { 2, 64ULL, 0ULL, 127439ULL, 2 },
    { 2, 64ULL, 0ULL, 29960ULL, 2 },
    { 2, 64ULL, 0ULL, 126945ULL, 2 },
    { 1, 0ULL, 16384ULL, 0ULL, 1 },
    { 1, 0ULL, 256ULL, 0ULL, 1 },
    { 1, 0ULL, 16384ULL, 0ULL, 1 },
};

static const struct trace_event tr_kmeans[] = {
    { 0, 524288ULL, 0ULL, 0ULL, 1 },
    { 0, 29920ULL, 0ULL, 0ULL, 1 },
    { 2, 60ULL, 0ULL, 845597ULL, 2 },
    { 0, 5120ULL, 0ULL, 0ULL, 1 },
    { 2, 76ULL, 0ULL, 2027869ULL, 2 },
    { 1, 0ULL, 2048ULL, 0ULL, 1 },
    { 0, 5120ULL, 0ULL, 0ULL, 1 },
    { 2, 76ULL, 0ULL, 2023789ULL, 2 },
    { 1, 0ULL, 2048ULL, 0ULL, 1 },
};

static const struct trace_event tr_lbm[] = {
    { 0, 1228800ULL, 0ULL, 0ULL, 1 },
    { 0, 1228800ULL, 0ULL, 0ULL, 1 },
    { 0, 30832ULL, 0ULL, 0ULL, 1 },
    { 2, 52ULL, 0ULL, 3198780ULL, 2 },
    { 1, 0ULL, 1228800ULL, 0ULL, 1 },
};

static const struct trace_event tr_nearn[] = {
    { 0, 171056ULL, 0ULL, 0ULL, 1 },
    { 0, 29536ULL, 0ULL, 0ULL, 1 },
    { 2, 64ULL, 0ULL, 616918ULL, 2 },
    { 1, 0ULL, 85528ULL, 0ULL, 1 },
};

static const struct trace_event tr_oclprintf[] = {
    { 0, 29624ULL, 0ULL, 0ULL, 1 },
    { 2, 80ULL, 0ULL, 69837ULL, 3 },
};

static const struct trace_event tr_psort[] = {
    { 0, 512ULL, 0ULL, 0ULL, 1 },
    { 0, 29768ULL, 0ULL, 0ULL, 1 },
    { 2, 52ULL, 0ULL, 99923ULL, 2 },
    { 1, 0ULL, 512ULL, 0ULL, 1 },
};

static const struct trace_event tr_psum[] = {
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 29824ULL, 0ULL, 0ULL, 1 },
    { 2, 64ULL, 0ULL, 118301ULL, 2 },
    { 1, 0ULL, 512ULL, 0ULL, 1 },
};

static const struct trace_event tr_saxpy[] = {
    { 0, 32768ULL, 0ULL, 0ULL, 1 },
    { 0, 32768ULL, 0ULL, 0ULL, 1 },
    { 0, 29496ULL, 0ULL, 0ULL, 1 },
    { 2, 56ULL, 0ULL, 282394ULL, 2 },
    { 1, 0ULL, 32768ULL, 0ULL, 1 },
};

static const struct trace_event tr_sfilter[] = {
    { 0, 16384ULL, 0ULL, 0ULL, 1 },
    { 0, 16384ULL, 0ULL, 0ULL, 1 },
    { 0, 29744ULL, 0ULL, 0ULL, 1 },
    { 2, 96ULL, 0ULL, 161119ULL, 2 },
    { 1, 0ULL, 16384ULL, 0ULL, 1 },
};

static const struct trace_event tr_sgemm[] = {
    { 0, 16384ULL, 0ULL, 0ULL, 1 },
    { 0, 16384ULL, 0ULL, 0ULL, 1 },
    { 0, 29584ULL, 0ULL, 0ULL, 1 },
    { 2, 60ULL, 0ULL, 622498ULL, 2 },
    { 1, 0ULL, 16384ULL, 0ULL, 1 },
};

static const struct trace_event tr_sgemm2[] = {
    { 0, 9216ULL, 0ULL, 0ULL, 1 },
    { 0, 9216ULL, 0ULL, 0ULL, 1 },
    { 0, 29952ULL, 0ULL, 0ULL, 1 },
    { 2, 72ULL, 0ULL, 541290ULL, 2 },
    { 1, 0ULL, 9216ULL, 0ULL, 1 },
};

static const struct trace_event tr_sgemm3[] = {
    { 0, 9216ULL, 0ULL, 0ULL, 1 },
    { 0, 9216ULL, 0ULL, 0ULL, 1 },
    { 0, 30008ULL, 0ULL, 0ULL, 1 },
    { 2, 72ULL, 0ULL, 566285ULL, 2 },
    { 1, 0ULL, 9216ULL, 0ULL, 1 },
};

static const struct trace_event tr_spmv[] = {
    { 0, 4552ULL, 0ULL, 0ULL, 1 },
    { 0, 17792ULL, 0ULL, 0ULL, 1 },
    { 0, 17792ULL, 0ULL, 0ULL, 1 },
    { 0, 4552ULL, 0ULL, 0ULL, 1 },
    { 0, 4552ULL, 0ULL, 0ULL, 1 },
    { 0, 29656ULL, 0ULL, 0ULL, 1 },
    { 2, 296ULL, 0ULL, 124630ULL, 4 },
    { 1, 0ULL, 4552ULL, 0ULL, 1 },
};

static const struct trace_event tr_stencil[] = {
    { 0, 32768ULL, 0ULL, 0ULL, 1 },
    { 0, 32768ULL, 0ULL, 0ULL, 1 },
    { 0, 29768ULL, 0ULL, 0ULL, 1 },
    { 2, 72ULL, 0ULL, 671828ULL, 2 },
    { 1, 0ULL, 32768ULL, 0ULL, 1 },
};

static const struct trace_event tr_transpose[] = {
    { 0, 1048576ULL, 0ULL, 0ULL, 1 },
    { 0, 30888ULL, 0ULL, 0ULL, 1 },
    { 2, 64ULL, 0ULL, 7858866ULL, 2 },
    { 2, 64ULL, 0ULL, 7883077ULL, 2 },
    { 1, 0ULL, 1048576ULL, 0ULL, 1 },
};

static const struct trace_event tr_vecadd[] = {
    { 0, 16384ULL, 0ULL, 0ULL, 1 },
    { 0, 16384ULL, 0ULL, 0ULL, 1 },
    { 0, 29496ULL, 0ULL, 0ULL, 1 },
    { 2, 56ULL, 0ULL, 154526ULL, 2 },
    { 1, 0ULL, 16384ULL, 0ULL, 1 },
};

struct trace_app {
    const char *name;
    const struct trace_event *events;
    size_t n;
};

static const struct trace_app jigsaw_traces[] = {
    { "bfs", tr_bfs, ARRAY_SIZE(tr_bfs) },
    { "blackscholes", tr_blackscholes, ARRAY_SIZE(tr_blackscholes) },
    { "conv3", tr_conv3, ARRAY_SIZE(tr_conv3) },
    { "dotproduct", tr_dotproduct, ARRAY_SIZE(tr_dotproduct) },
    { "guassian", tr_guassian, ARRAY_SIZE(tr_guassian) },
    { "kmeans", tr_kmeans, ARRAY_SIZE(tr_kmeans) },
    { "lbm", tr_lbm, ARRAY_SIZE(tr_lbm) },
    { "nearn", tr_nearn, ARRAY_SIZE(tr_nearn) },
    { "oclprintf", tr_oclprintf, ARRAY_SIZE(tr_oclprintf) },
    { "psort", tr_psort, ARRAY_SIZE(tr_psort) },
    { "psum", tr_psum, ARRAY_SIZE(tr_psum) },
    { "saxpy", tr_saxpy, ARRAY_SIZE(tr_saxpy) },
    { "sfilter", tr_sfilter, ARRAY_SIZE(tr_sfilter) },
    { "sgemm", tr_sgemm, ARRAY_SIZE(tr_sgemm) },
    { "sgemm2", tr_sgemm2, ARRAY_SIZE(tr_sgemm2) },
    { "sgemm3", tr_sgemm3, ARRAY_SIZE(tr_sgemm3) },
    { "spmv", tr_spmv, ARRAY_SIZE(tr_spmv) },
    { "stencil", tr_stencil, ARRAY_SIZE(tr_stencil) },
    { "transpose", tr_transpose, ARRAY_SIZE(tr_transpose) },
    { "vecadd", tr_vecadd, ARRAY_SIZE(tr_vecadd) },
};

#endif /* JIGSAW_TRACES_H */
