/* AUTO-GENERATED by extract_traces.py. Do not edit. */
/* Include from exactly one translation unit. */
#ifndef JIGSAW_TRACES_H
#define JIGSAW_TRACES_H

#include <linux/types.h>
#include <linux/kernel.h>  /* ARRAY_SIZE */

enum trace_kind {
    TRACE_BULK_H2D = 0,
    TRACE_BULK_D2H = 1,
    TRACE_BUNDLE   = 2,
};

struct trace_event {
    u8  kind;
    u64 h2d_size;       /* bytes; BULK_H2D, BUNDLE */
    u64 d2h_size;       /* bytes; BULK_D2H, BUNDLE */
    u64 cycles;         /* BUNDLE only */
    int original_count; /* raw events folded into this entry */
};

#define JIGSAW_TRACE_MAX_BYTES 1228800ULL
#define JIGSAW_BUNDLE_THRESHOLD 256ULL  /* small <=> <= this */

static const struct trace_event tr_bfs[] = {
    { 0, 32768ULL, 0ULL, 0ULL, 1 },
    { 0, 32768ULL, 0ULL, 0ULL, 1 },
    { 0, 98304ULL, 0ULL, 0ULL, 1 },
    { 0, 98304ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 16384ULL, 0ULL, 0ULL, 1 },
    { 0, 16384ULL, 0ULL, 0ULL, 1 },
    { 0, 29896ULL, 0ULL, 0ULL, 1 },
    { 2, 74ULL, 0ULL, 149573ULL, 4 },
    { 2, 64ULL, 1ULL, 136420ULL, 3 },
    { 2, 73ULL, 0ULL, 140956ULL, 3 },
    { 2, 64ULL, 1ULL, 130555ULL, 3 },
    { 2, 73ULL, 0ULL, 148911ULL, 3 },
    { 2, 64ULL, 1ULL, 135888ULL, 3 },
    { 2, 73ULL, 0ULL, 193950ULL, 3 },
    { 2, 64ULL, 1ULL, 147829ULL, 3 },
    { 2, 73ULL, 0ULL, 318273ULL, 3 },
    { 2, 64ULL, 1ULL, 146858ULL, 3 },
    { 2, 73ULL, 0ULL, 284353ULL, 3 },
    { 2, 64ULL, 1ULL, 135383ULL, 3 },
    { 2, 73ULL, 0ULL, 151490ULL, 3 },
    { 2, 64ULL, 1ULL, 136141ULL, 3 },
    { 2, 73ULL, 0ULL, 134923ULL, 3 },
    { 2, 64ULL, 1ULL, 129448ULL, 3 },
    { 1, 0ULL, 16384ULL, 0ULL, 1 },
};

static const struct trace_event tr_blackscholes[] = {
    { 0, 1024ULL, 0ULL, 0ULL, 1 },
    { 0, 1024ULL, 0ULL, 0ULL, 1 },
    { 0, 1024ULL, 0ULL, 0ULL, 1 },
    { 0, 33608ULL, 0ULL, 0ULL, 1 },
    { 2, 76ULL, 0ULL, 3102206ULL, 2 },
    { 1, 0ULL, 1024ULL, 0ULL, 1 },
    { 1, 0ULL, 1024ULL, 0ULL, 1 },
};

static const struct trace_event tr_conv3[] = {
    { 0, 4624ULL, 0ULL, 0ULL, 1 },
    { 0, 29736ULL, 0ULL, 0ULL, 1 },
    { 2, 100ULL, 0ULL, 68418ULL, 3 },
    { 1, 0ULL, 4096ULL, 0ULL, 1 },
};

static const struct trace_event tr_dotproduct[] = {
    { 0, 65536ULL, 0ULL, 0ULL, 1 },
    { 0, 65536ULL, 0ULL, 0ULL, 1 },
    { 0, 29592ULL, 0ULL, 0ULL, 1 },
    { 2, 60ULL, 0ULL, 228039ULL, 2 },
    { 1, 0ULL, 16384ULL, 0ULL, 1 },
};

static const struct trace_event tr_guassian[] = {
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 29880ULL, 0ULL, 0ULL, 1 },
    { 2, 192ULL, 0ULL, 30097ULL, 3 },
    { 2, 64ULL, 0ULL, 59657ULL, 2 },
    { 2, 64ULL, 0ULL, 25774ULL, 2 },
    { 2, 64ULL, 0ULL, 54959ULL, 2 },
    { 2, 64ULL, 0ULL, 26091ULL, 2 },
    { 2, 64ULL, 0ULL, 53996ULL, 2 },
    { 2, 64ULL, 0ULL, 26080ULL, 2 },
    { 2, 64ULL, 0ULL, 54029ULL, 2 },
    { 2, 64ULL, 0ULL, 26056ULL, 2 },
    { 2, 64ULL, 0ULL, 55152ULL, 2 },
    { 2, 64ULL, 0ULL, 26086ULL, 2 },
    { 2, 64ULL, 0ULL, 53839ULL, 2 },
    { 2, 64ULL, 0ULL, 25986ULL, 2 },
    { 2, 64ULL, 0ULL, 53958ULL, 2 },
    { 2, 64ULL, 0ULL, 26138ULL, 2 },
    { 2, 64ULL, 0ULL, 53388ULL, 2 },
    { 2, 64ULL, 0ULL, 26034ULL, 2 },
    { 2, 64ULL, 0ULL, 53387ULL, 2 },
    { 2, 64ULL, 0ULL, 26052ULL, 2 },
    { 2, 64ULL, 0ULL, 54107ULL, 2 },
    { 2, 64ULL, 0ULL, 25926ULL, 2 },
    { 2, 64ULL, 0ULL, 54358ULL, 2 },
    { 2, 64ULL, 0ULL, 25951ULL, 2 },
    { 2, 64ULL, 0ULL, 53830ULL, 2 },
    { 2, 64ULL, 0ULL, 26009ULL, 2 },
    { 2, 64ULL, 0ULL, 54522ULL, 2 },
    { 2, 64ULL, 0ULL, 25940ULL, 2 },
    { 2, 64ULL, 0ULL, 54268ULL, 2 },
    { 2, 64ULL, 0ULL, 25875ULL, 2 },
    { 2, 64ULL, 0ULL, 55005ULL, 2 },
    { 2, 64ULL, 0ULL, 25943ULL, 2 },
    { 2, 64ULL, 0ULL, 55259ULL, 2 },
    { 2, 64ULL, 0ULL, 25928ULL, 2 },
    { 2, 64ULL, 0ULL, 55229ULL, 2 },
    { 2, 64ULL, 0ULL, 25468ULL, 2 },
    { 2, 64ULL, 0ULL, 53627ULL, 2 },
    { 2, 64ULL, 0ULL, 25887ULL, 2 },
    { 2, 64ULL, 0ULL, 53310ULL, 2 },
    { 2, 64ULL, 0ULL, 25923ULL, 2 },
    { 2, 64ULL, 0ULL, 53045ULL, 2 },
    { 2, 64ULL, 0ULL, 25836ULL, 2 },
    { 2, 64ULL, 0ULL, 52710ULL, 2 },
    { 2, 64ULL, 0ULL, 25858ULL, 2 },
    { 2, 64ULL, 0ULL, 54043ULL, 2 },
    { 2, 64ULL, 0ULL, 26029ULL, 2 },
    { 2, 64ULL, 0ULL, 54081ULL, 2 },
    { 2, 64ULL, 0ULL, 25930ULL, 2 },
    { 2, 64ULL, 0ULL, 52786ULL, 2 },
    { 2, 64ULL, 0ULL, 25837ULL, 2 },
    { 2, 64ULL, 0ULL, 52760ULL, 2 },
    { 2, 64ULL, 0ULL, 25822ULL, 2 },
    { 2, 64ULL, 0ULL, 52820ULL, 2 },
    { 2, 64ULL, 0ULL, 25816ULL, 2 },
    { 2, 64ULL, 0ULL, 52804ULL, 2 },
    { 2, 64ULL, 0ULL, 25597ULL, 2 },
    { 2, 64ULL, 0ULL, 52340ULL, 2 },
    { 2, 64ULL, 0ULL, 25587ULL, 2 },
    { 2, 64ULL, 0ULL, 52511ULL, 2 },
    { 2, 64ULL, 0ULL, 25986ULL, 2 },
    { 2, 64ULL, 0ULL, 53640ULL, 2 },
    { 2, 64ULL, 0ULL, 25976ULL, 2 },
    { 2, 64ULL, 0ULL, 52930ULL, 2 },
    { 1, 0ULL, 4096ULL, 0ULL, 1 },
    { 1, 0ULL, 128ULL, 0ULL, 1 },
    { 1, 0ULL, 4096ULL, 0ULL, 1 },
};

static const struct trace_event tr_kmeans[] = {
    { 0, 40000ULL, 0ULL, 0ULL, 1 },
    { 0, 29920ULL, 0ULL, 0ULL, 1 },
    { 2, 60ULL, 0ULL, 73656ULL, 2 },
    { 0, 2000ULL, 0ULL, 0ULL, 1 },
    { 2, 76ULL, 0ULL, 209169ULL, 2 },
    { 1, 0ULL, 400ULL, 0ULL, 1 },
    { 0, 2000ULL, 0ULL, 0ULL, 1 },
    { 2, 76ULL, 0ULL, 207918ULL, 2 },
    { 1, 0ULL, 400ULL, 0ULL, 1 },
};

static const struct trace_event tr_lbm[] = {
    { 0, 1228800ULL, 0ULL, 0ULL, 1 },
    { 0, 1228800ULL, 0ULL, 0ULL, 1 },
    { 0, 30832ULL, 0ULL, 0ULL, 1 },
    { 2, 52ULL, 0ULL, 3198780ULL, 2 },
    { 1, 0ULL, 1228800ULL, 0ULL, 1 },
};

static const struct trace_event tr_nearn[] = {
    { 0, 171056ULL, 0ULL, 0ULL, 1 },
    { 0, 29536ULL, 0ULL, 0ULL, 1 },
    { 2, 64ULL, 0ULL, 616918ULL, 2 },
    { 1, 0ULL, 85528ULL, 0ULL, 1 },
};

static const struct trace_event tr_oclprintf[] = {
    { 0, 29624ULL, 0ULL, 0ULL, 1 },
    { 2, 64ULL, 0ULL, 68554ULL, 3 },
};

static const struct trace_event tr_psort[] = {
    { 0, 29768ULL, 0ULL, 0ULL, 1 },
    { 2, 116ULL, 64ULL, 28870ULL, 4 },
};

static const struct trace_event tr_psum[] = {
    { 0, 29824ULL, 0ULL, 0ULL, 1 },
    { 2, 128ULL, 8ULL, 27995ULL, 4 },
};

static const struct trace_event tr_saxpy[] = {
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 29496ULL, 0ULL, 0ULL, 1 },
    { 2, 56ULL, 0ULL, 60800ULL, 2 },
    { 1, 0ULL, 4096ULL, 0ULL, 1 },
};

static const struct trace_event tr_sfilter[] = {
    { 0, 1024ULL, 0ULL, 0ULL, 1 },
    { 0, 1024ULL, 0ULL, 0ULL, 1 },
    { 0, 29744ULL, 0ULL, 0ULL, 1 },
    { 2, 96ULL, 0ULL, 41787ULL, 2 },
    { 1, 0ULL, 1024ULL, 0ULL, 1 },
};

static const struct trace_event tr_sgemm[] = {
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 4096ULL, 0ULL, 0ULL, 1 },
    { 0, 29584ULL, 0ULL, 0ULL, 1 },
    { 2, 60ULL, 0ULL, 109156ULL, 2 },
    { 1, 0ULL, 4096ULL, 0ULL, 1 },
};

static const struct trace_event tr_sgemm2[] = {
    { 0, 1024ULL, 0ULL, 0ULL, 1 },
    { 0, 1024ULL, 0ULL, 0ULL, 1 },
    { 0, 29952ULL, 0ULL, 0ULL, 1 },
    { 2, 72ULL, 0ULL, 74177ULL, 2 },
    { 1, 0ULL, 1024ULL, 0ULL, 1 },
};

static const struct trace_event tr_sgemm3[] = {
    { 0, 1024ULL, 0ULL, 0ULL, 1 },
    { 0, 1024ULL, 0ULL, 0ULL, 1 },
    { 0, 30008ULL, 0ULL, 0ULL, 1 },
    { 2, 72ULL, 0ULL, 70845ULL, 2 },
    { 1, 0ULL, 1024ULL, 0ULL, 1 },
};

static const struct trace_event tr_spmv[] = {
    { 0, 4552ULL, 0ULL, 0ULL, 1 },
    { 0, 17792ULL, 0ULL, 0ULL, 1 },
    { 0, 17792ULL, 0ULL, 0ULL, 1 },
    { 0, 4552ULL, 0ULL, 0ULL, 1 },
    { 0, 4552ULL, 0ULL, 0ULL, 1 },
    { 0, 29656ULL, 0ULL, 0ULL, 1 },
    { 2, 296ULL, 0ULL, 124630ULL, 4 },
    { 1, 0ULL, 4552ULL, 0ULL, 1 },
};

static const struct trace_event tr_stencil[] = {
    { 0, 32768ULL, 0ULL, 0ULL, 1 },
    { 0, 32768ULL, 0ULL, 0ULL, 1 },
    { 0, 29768ULL, 0ULL, 0ULL, 1 },
    { 2, 72ULL, 0ULL, 671828ULL, 2 },
    { 1, 0ULL, 32768ULL, 0ULL, 1 },
};

static const struct trace_event tr_transpose[] = {
    { 0, 65536ULL, 0ULL, 0ULL, 1 },
    { 0, 30888ULL, 0ULL, 0ULL, 1 },
    { 2, 64ULL, 0ULL, 531888ULL, 2 },
    { 2, 64ULL, 0ULL, 516368ULL, 2 },
    { 1, 0ULL, 65536ULL, 0ULL, 1 },
};

static const struct trace_event tr_vecadd[] = {
    { 0, 29496ULL, 0ULL, 0ULL, 1 },
    { 2, 568ULL, 256ULL, 34893ULL, 5 },
};

struct trace_app {
    const char *name;
    const struct trace_event *events;
    size_t n;
};

static const struct trace_app jigsaw_traces[] = {
    { "bfs", tr_bfs, ARRAY_SIZE(tr_bfs) },
    { "blackscholes", tr_blackscholes, ARRAY_SIZE(tr_blackscholes) },
    { "conv3", tr_conv3, ARRAY_SIZE(tr_conv3) },
    { "dotproduct", tr_dotproduct, ARRAY_SIZE(tr_dotproduct) },
    { "guassian", tr_guassian, ARRAY_SIZE(tr_guassian) },
    { "kmeans", tr_kmeans, ARRAY_SIZE(tr_kmeans) },
    { "lbm", tr_lbm, ARRAY_SIZE(tr_lbm) },
    { "nearn", tr_nearn, ARRAY_SIZE(tr_nearn) },
    { "oclprintf", tr_oclprintf, ARRAY_SIZE(tr_oclprintf) },
    { "psort", tr_psort, ARRAY_SIZE(tr_psort) },
    { "psum", tr_psum, ARRAY_SIZE(tr_psum) },
    { "saxpy", tr_saxpy, ARRAY_SIZE(tr_saxpy) },
    { "sfilter", tr_sfilter, ARRAY_SIZE(tr_sfilter) },
    { "sgemm", tr_sgemm, ARRAY_SIZE(tr_sgemm) },
    { "sgemm2", tr_sgemm2, ARRAY_SIZE(tr_sgemm2) },
    { "sgemm3", tr_sgemm3, ARRAY_SIZE(tr_sgemm3) },
    { "spmv", tr_spmv, ARRAY_SIZE(tr_spmv) },
    { "stencil", tr_stencil, ARRAY_SIZE(tr_stencil) },
    { "transpose", tr_transpose, ARRAY_SIZE(tr_transpose) },
    { "vecadd", tr_vecadd, ARRAY_SIZE(tr_vecadd) },
};

#endif /* JIGSAW_TRACES_H */
